name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.1
        with:
          command: spectral --version

      - name: asdf_plugin_test_6_5_0
        uses: asdf-vm/actions/plugin-test@v1.0.1
        with:
          command: spectral --version
          version: 6.5.0

      - name: asdf_plugin_test_6_6_0
        uses: asdf-vm/actions/plugin-test@v1.0.1
        with:
          command: spectral --version
          version: 6.6.0

      - name: asdf_plugin_test_6_7_0
        uses: asdf-vm/actions/plugin-test@v1.0.1
        with:
          command: spectral --version
          version: 6.7.0

      - name: asdf_plugin_test_6_11_1
        uses: asdf-vm/actions/plugin-test@v1.0.1
        with:
          command: spectral --version
          version: 6.11.1